[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "thelib"
version = "0.1.0"
description = "demo example package"
authors = [{name = "Ipo", email = "possantti@gmail.com"}]
