[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "thelib"
authors = [{name = "Ipo", email = "possantti@gmail.com"}]
dynamic = ["version", "description"]
